### ISSUE TITLE
Bootloader unlock on RMX1921L1

### ISSUE THREAD

**Issue by ThatisJigen** [realme-kernel-opensource/realme3Pro_realmeXT_AndroidQ-kernel-source#3]
What's the meaning of giving sources without a tool to unlock bl in europe?
Seems like EU devices are class 2 devices

**Comment by realme-kernel-opensource** [comment]
font{
        line-height: 1.7;
    }


    

hi,sir got it.we are checking.                



    On 5/2/2020 23:13，Jigen<notifications@github.com> wrote： 



What's the meaning of giving sources without a tool to unlock bl in europe?
Seems like EU devices are class 2 devices

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by ThatisJigen** [comment]
thanks for the answer, I'll wait any news

**Comment by usamaiqbal1177** [comment]
Same issue as @ThatisJigen plz fix it!!! 😢

**Comment by GiaSen** [comment]
Same here, help please

**Comment by Erickeagle3** [comment]
Me facing same please fix that issue please

**Comment by smokey18** [comment]
please let us unlock bootloader

**Comment by LordShenron** [comment]
"The rising smartphone brand releases sources but won't let you unlock bootloader :3"

**Comment by realme-kernel-opensource** [comment]
hi, everyone:
pls help provide the getprop ro.product.name,we will check futher more.

**Comment by ThatisJigen** [comment]
![IMG_20200511_092836](https://user-images.githubusercontent.com/55486333/81535293-d570a580-9369-11ea-90ab-28b63e27caf3.jpg)
RMX1921 EEA

**Comment by saikrishnawanted** [comment]
> hi, everyone:
> pls help provide the getprop ro.product.name,we will check futher more.

Lol, what!
Should we all laugh or feel sad about this.

**Comment by LordShenron** [comment]
> hi, everyone:
> pls help provide the getprop ro.product.name,we will check futher more.

Looks like realme developers don't actually have the device xd

**Comment by ThatisJigen** [comment]
Bootloader unlocked, will wait for your confirmation and close the issue.

**Comment by ioshkin** [comment]
> Bootloader unlocked, will wait for your confirmation and close the issue.

where to download the unlocker app?

**Comment by ThatisJigen** [comment]
> > Bootloader unlocked, will wait for your confirmation and close the issue.
> 
> where to download the unlocker app?
https://c.realme.com/in/post-details/1247848106351919104 if you confirm it's working i'll close

**Comment by ioshkin** [comment]
> > where to download the unlocker app?
> 
> https://c.realme.com/in/post-details/1247848106351919104
> confirm if working and i'll close the issue, for me it's okay, I'm already testing a custom rom

Yes. It worked for me.

**Comment by ThatisJigen** [comment]
> > > where to download the unlocker app?
> > 
> > 
> > https://c.realme.com/in/post-details/1247848106351919104
> > confirm if working and i'll close the issue, for me it's okay, I'm already testing a custom rom
> 
> Yes. It worked for me.

OK, thanks realme, finally
